$primary = rgb(bd93f9)
$surface = rgb(282a36)
$secondary = rgb(ff79c6)
$error = rgb(ff5555)
$tertiary = rgb(8be9fd)
$surface_lowest = rgb(2d2f3d)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
