################
### MONITORS ###
################

monitor=,preferred,auto,1.25

###################
### MY PROGRAMS ###
###################

# Set programs that you use
$terminal = ghostty 
$fileManager = thunar
$menu = qs -c noctalia-shell ipc call launcher toggle 
$browser = zen-browser 


source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/plugin.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/noctalia/noctalia-colors.conf

xwayland {
  force_zero_scaling = true
}
