[main]
include=~/.config/foot/themes/noctalia

title=Foot
app-id=Foot
locked-title=yes

font=IosevkaNerdFont-Regular:size=14
font-bold=IosevkaNerdFont-Bold:size=14
font-italic=IosevkaNerdFont-Italic:size=14
font-bold-italic=IosevkaNerdFont-BoldItalic:size=14

pad=12x12 center-when-maximized-and-fullscreen

[colors-dark]
# background=282a36
# foreground=f8f8f2
alpha=0.7

# regular0=21222c  # black
# regular1=ff5555  # red
# regular2=50fa7b  # green
# regular3=f1fa8c  # yellow
# regular4=bd93f9  # blue
# regular5=ff79c6  # magenta
# regular6=8be9fd  # cyan
# regular7=f8f8f2  # white

# bright0=6272a4   # bright black
# bright1=ff6e6e   # bright red
# bright2=69ff94   # bright green
# bright3=ffffa5   # bright yellow
# bright4=d6acff   # bright blue
# bright5=ff92df   # bright magenta
# bright6=a4ffff   # bright cyan
# bright7=ffffff   # bright white

[bell]
system=no
urgent=no
notify=no
visual=no

[scrollback]
lines=2000
multiplier=3.0

[cursor]
style=block
blink=no
blink-rate=500
beam-thickness=1.5

[mouse]
hide-when-typing=yes

[key-bindings]
fullscreen = Control+Return
