format = """
[░▒▓](#2e3440)\
$os\
$username\
[](bg:#3b4252 fg:#2e3440)\
$directory\
[](fg:#3b4252 bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#4c566a)\
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4c566a bg:#5e81ac)\
$docker_context\
[](fg:#5e81ac bg:#6272a4)\
$time\
[ ](fg:#6272a4)\
\n$character"""
#add_newline = false

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:#2e3440"
style_root = "bg:#9A348E"
format = '[  $user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:##434c5e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%l:%M %p" # Hour:Minute Format
style = "bg:#6272a4"
format = '[   $time ]($style)'
